#端口号
server:
  port: 8099
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /


#  环境
spring:
  profiles:
    active: dev
    jmx: false
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  mvc:
    async:
      request-timeout: 120
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                 #数据库连接池的最小维持连接数;
      initial-size: 5                             #初始化提供的连接数
      max-total: 10                               # 最大的连接数
      max-wait-millis: 200                        # 等待连接获取的最大超时时间

  redis:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1ms
        max-idle: 8
  aop:
    auto: true
    proxy-target-class: true
mybatis:
  mapper-locations: mapper/**/*.xml

