spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhuxf_test?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  redis:
    host: 123.56.26.9
    password:
    database: 0
    port: 9612

logging:
  level:
    root: INFO
    com: debug
  path: concretepage/logs
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
  file: practice.log

